# Generated by Django 5.2 on 2025-04-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')]),
        ),
    ]
