# Generated by Django 5.2 on 2025-04-28 17:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_reaction_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'comment')},
        ),
    ]
