# Generated by Django 5.2 on 2025-04-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_comments_reaction_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.IntegerField(choices=[(1, 'like'), (-1, 'dislike'), (0, 'neutral')]),
        ),
    ]
