# Generated by Django 5.2 on 2025-04-29 13:36

import base.custom_validators
import comments.models.comments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_reaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=comments.models.comments.Comment.get_upload_url, validators=[base.custom_validators.FileValidator()]),
        ),
    ]
